// ... (código existente, apenas pequenas alterações para garantir compatibilidade) ...
// Este componente não faz queries diretas ao banco, então não precisa de alterações.
// ... (restante do código existente) ...