// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtskautbkbhqwinuassp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0c2thdXRia2JocXdpbnVhc3NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4OTEwMjcsImV4cCI6MjA3NjQ2NzAyN30.EqQChO6dPqP0YHWVkyzPT2cXcIzkvm1WqLblU9bfNmM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});